import React from 'react';

import Page from 'app/components/Page';
import Navbar from 'app/containers/Navbar';
import Container from 'app/components/Container';

interface Props {
}

const HomePage = (_props: Props): React.ReactElement => {
  return (
    <Page
      title='Home'
    >
      <Navbar />
      <Container>
        <p className='mt-3 mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris rhoncus turpis eu laoreet vulputate. Aenean pretium sem dui, sit amet accumsan libero posuere in. Mauris eget suscipit nibh. Phasellus scelerisque orci eget lorem egestas, nec imperdiet mauris euismod. Vestibulum nibh elit, malesuada ac blandit at, posuere in urna. Pellentesque cursus justo sollicitudin, molestie nulla at, sagittis mauris. Nam consectetur ligula id tristique fermentum. Suspendisse eu molestie magna. Curabitur pulvinar sodales gravida. Duis orci neque, tincidunt non tortor in, consectetur dapibus massa. Integer egestas scelerisque convallis. Praesent nec blandit nunc. Ut eget sem eu turpis rhoncus maximus.</p>
        <p className='mt-3 mb-3'>Mauris vitae feugiat risus, a rhoncus ipsum. Vestibulum vitae sodales nisl, eget euismod urna. Suspendisse at pellentesque massa. In id tincidunt diam, ut faucibus enim. Integer porttitor mattis orci, et rhoncus mi ornare id. Nullam porttitor, nisi eu ultricies scelerisque, ligula neque auctor quam, et bibendum leo ante vel neque. Nullam tempor euismod lacus, eget tempor enim volutpat id. Etiam euismod magna at lacus egestas tristique. Aliquam tincidunt auctor tellus et feugiat.</p>
        <p className='mt-3 mb-3'>Duis in facilisis tortor. Sed consequat tincidunt arcu eu convallis. Duis hendrerit justo nisl, ut tincidunt nisl laoreet ut. Quisque egestas bibendum justo, sit amet gravida nulla venenatis eu. Sed molestie vitae magna nec tempus. Proin et egestas eros, vitae elementum odio. Phasellus blandit dui quis libero tempus, eu tincidunt tortor imperdiet. Vestibulum pharetra, ipsum eu vulputate eleifend, augue est ultricies enim, nec malesuada dui urna a felis. Nam tortor nisi, vehicula vel arcu quis, convallis rutrum libero. Nunc elit ligula, fringilla sit amet ullamcorper eget, rhoncus eget purus. Etiam semper, mauris et sagittis congue, nibh tellus cursus tortor, quis pulvinar ligula dui in enim. Donec sed iaculis enim, sed tristique ipsum. Aliquam vehicula eros ut nunc mattis, at consectetur nibh gravida. Mauris vel felis sit amet leo varius viverra ac nec neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <p className='mt-3 mb-3'>Praesent iaculis molestie risus. Vivamus fermentum orci at aliquam venenatis. Nulla facilisi. Mauris id dui imperdiet, sagittis mauris eget, finibus ligula. Morbi sed eros neque. Donec ultricies finibus mauris sit amet efficitur. Ut bibendum dapibus est, ac gravida sem varius sit amet.</p>
        <p className='mt-3 mb-3'>Sed ut hendrerit orci. Proin elementum mattis quam, ut porttitor arcu suscipit eget. Phasellus tristique vel nulla non mattis. Phasellus et tristique ipsum. Vivamus odio turpis, porta sed ex a, viverra sagittis justo. Curabitur magna purus, maximus nec suscipit id, convallis ac eros. Pellentesque venenatis ipsum ut sapien rhoncus, at egestas metus viverra. Etiam ut hendrerit ante. Proin congue pulvinar nisi non viverra. Integer varius libero blandit neque malesuada, eget faucibus elit egestas.</p>
        <p className='mt-3 mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris rhoncus turpis eu laoreet vulputate. Aenean pretium sem dui, sit amet accumsan libero posuere in. Mauris eget suscipit nibh. Phasellus scelerisque orci eget lorem egestas, nec imperdiet mauris euismod. Vestibulum nibh elit, malesuada ac blandit at, posuere in urna. Pellentesque cursus justo sollicitudin, molestie nulla at, sagittis mauris. Nam consectetur ligula id tristique fermentum. Suspendisse eu molestie magna. Curabitur pulvinar sodales gravida. Duis orci neque, tincidunt non tortor in, consectetur dapibus massa. Integer egestas scelerisque convallis. Praesent nec blandit nunc. Ut eget sem eu turpis rhoncus maximus.</p>
        <p className='mt-3 mb-3'>Mauris vitae feugiat risus, a rhoncus ipsum. Vestibulum vitae sodales nisl, eget euismod urna. Suspendisse at pellentesque massa. In id tincidunt diam, ut faucibus enim. Integer porttitor mattis orci, et rhoncus mi ornare id. Nullam porttitor, nisi eu ultricies scelerisque, ligula neque auctor quam, et bibendum leo ante vel neque. Nullam tempor euismod lacus, eget tempor enim volutpat id. Etiam euismod magna at lacus egestas tristique. Aliquam tincidunt auctor tellus et feugiat.</p>
        <p className='mt-3 mb-3'>Duis in facilisis tortor. Sed consequat tincidunt arcu eu convallis. Duis hendrerit justo nisl, ut tincidunt nisl laoreet ut. Quisque egestas bibendum justo, sit amet gravida nulla venenatis eu. Sed molestie vitae magna nec tempus. Proin et egestas eros, vitae elementum odio. Phasellus blandit dui quis libero tempus, eu tincidunt tortor imperdiet. Vestibulum pharetra, ipsum eu vulputate eleifend, augue est ultricies enim, nec malesuada dui urna a felis. Nam tortor nisi, vehicula vel arcu quis, convallis rutrum libero. Nunc elit ligula, fringilla sit amet ullamcorper eget, rhoncus eget purus. Etiam semper, mauris et sagittis congue, nibh tellus cursus tortor, quis pulvinar ligula dui in enim. Donec sed iaculis enim, sed tristique ipsum. Aliquam vehicula eros ut nunc mattis, at consectetur nibh gravida. Mauris vel felis sit amet leo varius viverra ac nec neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <p className='mt-3 mb-3'>Praesent iaculis molestie risus. Vivamus fermentum orci at aliquam venenatis. Nulla facilisi. Mauris id dui imperdiet, sagittis mauris eget, finibus ligula. Morbi sed eros neque. Donec ultricies finibus mauris sit amet efficitur. Ut bibendum dapibus est, ac gravida sem varius sit amet.</p>
        <p className='mt-3 mb-3'>Sed ut hendrerit orci. Proin elementum mattis quam, ut porttitor arcu suscipit eget. Phasellus tristique vel nulla non mattis. Phasellus et tristique ipsum. Vivamus odio turpis, porta sed ex a, viverra sagittis justo. Curabitur magna purus, maximus nec suscipit id, convallis ac eros. Pellentesque venenatis ipsum ut sapien rhoncus, at egestas metus viverra. Etiam ut hendrerit ante. Proin congue pulvinar nisi non viverra. Integer varius libero blandit neque malesuada, eget faucibus elit egestas.</p>
      </Container>
    </Page>
  );
};

export default HomePage;
